### ISSUE TITLE
Duplicate red bar with nickname 

### ISSUE THREAD

**Issue by mestrade** [unix4fun/ac#5]
when re-enabling encryption after peer was disconnected, after /pk and /sk, when the encryption is enabled again, the red nickname bar is duplicated.

**Comment by eau-u4f** [comment]
it's also a very important bug you found as it makes you think you are speaking "encrypted" while it's unencrypted (no crypto context exist for the new nick aka the daemon is unaware of it), mainly due to the fact that the plugin does not follow (yet) nickchanges and update the context accordingly.

**Comment by eau-u4f** [comment]
the bar display has been rewritten and this should fix this issue :)
