### ISSUE TITLE
IC / weechat is dropping accentuated messages

### ISSUE THREAD

**Issue by mguegan** [unix4fun/ac#9]
When the sender is writing with accentuated character, his messages are never seen by the receiver. As far as I know, no error messages are given, so its almost impossible for the sender to know about this problem.

**Comment by eau-u4f** [comment]
added a string encoding before display to prepare the data to arrive as utf-8 (default charset internal to weechat) but it's not a proper solution, will work out a proper charset handling according to weechat config in the next coming push.

str.encode("utf-8")

in the meantime this fixes the issue.
